Models/Canbo.cs
using System;
using System.Collections.Generic;

namespace QLTHPT.Models
{
    public partial class Canbo
    {
        public Canbo()
        {
            ChitietChucvu = new HashSet<ChitietChucvu>();
            Thoikhoabieu = new HashSet<Thoikhoabieu>();
            Thongtindaotao = new HashSet<Thongtindaotao>();
            Thongtinluong = new HashSet<Thongtinluong>();
        }

        public string CbMa { get; set; }
        public string CbHoten { get; set; }
        public string CbGioitinh { get; set; }
        public string CbDiachi { get; set; }
        public DateTime? CbNgaysinh { get; set; }
        public string CbCmnd { get; set; }
        public string CoquanCqMa { get; set; }
        public string KyluatcbKlcbMa { get; set; }
        public string KhenthuongcbKtcbMa { get; set; }

        public virtual Coquan CoquanCqMaNavigation { get; set; }
        public virtual Khenthuongcb KhenthuongcbKtcbMaNavigation { get; set; }
        public virtual Kyluatcb KyluatcbKlcbMaNavigation { get; set; }
        public virtual ICollection<ChitietChucvu> ChitietChucvu { get; set; }
        public virtual ICollection<Thoikhoabieu> Thoikhoabieu { get; set; }
        public virtual ICollection<Thongtindaotao> Thongtindaotao { get; set; }
        public virtual ICollection<Thongtinluong> Thongtinluong { get; set; }
    }
}

Controllers/CanbosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using QLTHPT.Models;

namespace QLTHPT.Controllers {
    public class CanbosController : Controller {
        private readonly acomptec_qlthptContext _context = new acomptec_qlthptContext();

        // GET: Canbos
        public async Task<IActionResult> Index () {
            var acomptec_qlthptContext = _context.Canbo.Include (c => c.CoquanCqMaNavigation).Include (c => c.KhenthuongcbKtcbMaNavigation).Include (c => c.KyluatcbKlcbMaNavigation);
            return View (await acomptec_qlthptContext.ToListAsync ());
        }

        // GET: Canbos/Details/5
        public async Task<IActionResult> Details (string id) {
            if (id == null) {
                return NotFound ();
            }

            var canbo = await _context.Canbo
                .Include (c => c.CoquanCqMaNavigation)
                .Include (c => c.KhenthuongcbKtcbMaNavigation)
                .Include (c => c.KyluatcbKlcbMaNavigation)
                .FirstOrDefaultAsync (m => m.CbMa == id);
            if (canbo == null) {
                return NotFound ();
            }

            return View (canbo);
        }

        public async Task<IActionResult> Print (string id) {
            if (id == null) {
                return NotFound ();
            }

            var canbo = await _context.Canbo
                .FirstOrDefaultAsync (m => m.CbMa == id);
            if (canbo == null) {
                return NotFound ();
            }

            return View (canbo);
        }

        // GET: Canbos/Create
        public IActionResult Create () {
            ViewData["CoquanCqMa"] = new SelectList (_context.Coquan, "CqMa", "CqMa");
            ViewData["KhenthuongcbKtcbMa"] = new SelectList (_context.Khenthuongcb, "KtcbMa", "KtcbMa");
            ViewData["KyluatcbKlcbMa"] = new SelectList (_context.Kyluatcb, "KlcbMa", "KlcbMa");
            return View();
        }

        // POST: Canbos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create ([Bind ("CbMa,CbHoten,CbGioitinh,CbDiachi,CbNgaysinh,CbCmnd,CoquanCqMa,KyluatcbKlcbMa,KhenthuongcbKtcbMa")] Canbo canbo) {
            if (ModelState.IsValid) {
                _context.Add (canbo);
                await _context.SaveChangesAsync ();
                return RedirectToAction (nameof (Index));
            }
            ViewData["CoquanCqMa"] = new SelectList (_context.Coquan, "CqMa", "CqMa", canbo.CoquanCqMa);
            ViewData["KhenthuongcbKtcbMa"] = new SelectList (_context.Khenthuongcb, "KtcbMa", "KtcbMa", canbo.KhenthuongcbKtcbMa);
            ViewData["KyluatcbKlcbMa"] = new SelectList (_context.Kyluatcb, "KlcbMa", "KlcbMa", canbo.KyluatcbKlcbMa);
            return View (canbo);
        }

        // GET: Canbos/Edit/5
        public async Task<IActionResult> Edit (string id) {
            if (id == null) {
                return NotFound ();
            }

            var canbo = await _context.Canbo.FindAsync (id);
            if (canbo == null) {
                return NotFound ();
            }
            ViewData["CoquanCqMa"] = new SelectList (_context.Coquan, "CqMa", "CqMa", canbo.CoquanCqMa);
            ViewData["KhenthuongcbKtcbMa"] = new SelectList (_context.Khenthuongcb, "KtcbMa", "KtcbMa", canbo.KhenthuongcbKtcbMa);
            ViewData["KyluatcbKlcbMa"] = new SelectList (_context.Kyluatcb, "KlcbMa", "KlcbMa", canbo.KyluatcbKlcbMa);
            return View (canbo);
        }

        // POST: Canbos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit (string id, [Bind ("CbMa,CbHoten,CbGioitinh,CbDiachi,CbNgaysinh,CbCmnd,CoquanCqMa,KyluatcbKlcbMa,KhenthuongcbKtcbMa")] Canbo canbo) {
            if (id != canbo.CbMa) {
                return NotFound ();
            }

            if (ModelState.IsValid) {
                try {
                    _context.Update (canbo);
                    await _context.SaveChangesAsync ();
                } catch (DbUpdateConcurrencyException) {
                    if (!CanboExists (canbo.CbMa)) {
                        return NotFound ();
                    } else {
                        throw;
                    }
                }
                return RedirectToAction (nameof (Index));
            }
            ViewData["CoquanCqMa"] = new SelectList (_context.Coquan, "CqMa", "CqMa", canbo.CoquanCqMa);
            ViewData["KhenthuongcbKtcbMa"] = new SelectList (_context.Khenthuongcb, "KtcbMa", "KtcbMa", canbo.KhenthuongcbKtcbMa);
            ViewData["KyluatcbKlcbMa"] = new SelectList (_context.Kyluatcb, "KlcbMa", "KlcbMa", canbo.KyluatcbKlcbMa);
            return View (canbo);
        }

        // GET: Canbos/Delete/5
        public async Task<IActionResult> Delete (string id) {
            if (id == null) {
                return NotFound ();
            }

            var canbo = await _context.Canbo
                .Include (c => c.CoquanCqMaNavigation)
                .Include (c => c.KhenthuongcbKtcbMaNavigation)
                .Include (c => c.KyluatcbKlcbMaNavigation)
                .FirstOrDefaultAsync (m => m.CbMa == id);
            if (canbo == null) {
                return NotFound ();
            }

            return View (canbo);
        }

        // POST: Canbos/Delete/5
        [HttpPost, ActionName ("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed (string id) {
            var canbo = await _context.Canbo.FindAsync (id);
            _context.Canbo.Remove (canbo);
            await _context.SaveChangesAsync ();
            return RedirectToAction (nameof (Index));
        }

        private bool CanboExists (string id) {
            return _context.Canbo.Any (e => e.CbMa == id);
        }
    }
}

Views/Canbos/Create.cshtml
@model QLTHPT.Models.Canbo

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Canbo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CbMa" class="control-label"></label>
                <input asp-for="CbMa" class="form-control" />
                <span asp-validation-for="CbMa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CbHoten" class="control-label"></label>
                <input asp-for="CbHoten" class="form-control" />
                <span asp-validation-for="CbHoten" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CbGioitinh" class="control-label"></label>
                <input asp-for="CbGioitinh" class="form-control" />
                <span asp-validation-for="CbGioitinh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CbDiachi" class="control-label"></label>
                <input asp-for="CbDiachi" class="form-control" />
                <span asp-validation-for="CbDiachi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CbNgaysinh" class="control-label"></label>
                <input asp-for="CbNgaysinh" class="form-control" />
                <span asp-validation-for="CbNgaysinh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CbCmnd" class="control-label"></label>
                <input asp-for="CbCmnd" class="form-control" />
                <span asp-validation-for="CbCmnd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CoquanCqMa" class="control-label"></label>
                <select asp-for="CoquanCqMa" class ="form-control" asp-items="ViewBag.CoquanCqMa"></select>
            </div>
            <div class="form-group">
                <label asp-for="KyluatcbKlcbMa" class="control-label"></label>
                <select asp-for="KyluatcbKlcbMa" class ="form-control" asp-items="ViewBag.KyluatcbKlcbMa"></select>
            </div>
            <div class="form-group">
                <label asp-for="KhenthuongcbKtcbMa" class="control-label"></label>
                <select asp-for="KhenthuongcbKtcbMa" class ="form-control" asp-items="ViewBag.KhenthuongcbKtcbMa"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Canbos/Delete.cshtml
@model QLTHPT.Models.Canbo

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Canbo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CbHoten)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CbHoten)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CbGioitinh)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CbGioitinh)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CbDiachi)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CbDiachi)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CbNgaysinh)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CbNgaysinh)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CbCmnd)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CbCmnd)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CoquanCqMaNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CoquanCqMaNavigation.CqMa)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.KhenthuongcbKtcbMaNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.KhenthuongcbKtcbMaNavigation.KtcbMa)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.KyluatcbKlcbMaNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.KyluatcbKlcbMaNavigation.KlcbMa)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CbMa" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Canbos/Details.cshtml
@model QLTHPT.Models.Canbo

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Canbo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CbHoten)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CbHoten)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CbGioitinh)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CbGioitinh)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CbDiachi)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CbDiachi)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CbNgaysinh)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CbNgaysinh)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CbCmnd)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CbCmnd)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CoquanCqMaNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CoquanCqMaNavigation.CqMa)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.KhenthuongcbKtcbMaNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.KhenthuongcbKtcbMaNavigation.KtcbMa)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.KyluatcbKlcbMaNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.KyluatcbKlcbMaNavigation.KlcbMa)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.CbMa">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Canbos/Edit.cshtml
@model QLTHPT.Models.Canbo

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Canbo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CbMa" />
            <div class="form-group">
                <label asp-for="CbHoten" class="control-label"></label>
                <input asp-for="CbHoten" class="form-control" />
                <span asp-validation-for="CbHoten" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CbGioitinh" class="control-label"></label>
                <input asp-for="CbGioitinh" class="form-control" />
                <span asp-validation-for="CbGioitinh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CbDiachi" class="control-label"></label>
                <input asp-for="CbDiachi" class="form-control" />
                <span asp-validation-for="CbDiachi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CbNgaysinh" class="control-label"></label>
                <input asp-for="CbNgaysinh" class="form-control" />
                <span asp-validation-for="CbNgaysinh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CbCmnd" class="control-label"></label>
                <input asp-for="CbCmnd" class="form-control" />
                <span asp-validation-for="CbCmnd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CoquanCqMa" class="control-label"></label>
                <select asp-for="CoquanCqMa" class="form-control" asp-items="ViewBag.CoquanCqMa"></select>
                <span asp-validation-for="CoquanCqMa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="KyluatcbKlcbMa" class="control-label"></label>
                <select asp-for="KyluatcbKlcbMa" class="form-control" asp-items="ViewBag.KyluatcbKlcbMa"></select>
                <span asp-validation-for="KyluatcbKlcbMa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="KhenthuongcbKtcbMa" class="control-label"></label>
                <select asp-for="KhenthuongcbKtcbMa" class="form-control" asp-items="ViewBag.KhenthuongcbKtcbMa"></select>
                <span asp-validation-for="KhenthuongcbKtcbMa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Canbos/Index.cshtml
@model IEnumerable<QLTHPT.Models.Canbo>

@{
    ViewData["Title"] = "Index";
}

<div class="data-table-area mg-b-15">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="sparkline13-list shadow-reset">
                    <div class="sparkline13-hd">
                        <div class="main-sparkline13-hd">
                            <h4><strong>CÁN BỘ</strong></h4>
                        </div>
                    </div>
                    <div class="sparkline13-graph">
                        <div class="datatable-dashv1-list custom-datatable-overright">
                            <div id="toolbar">
                                <strong>@Html.ActionLink("Tạo Mới", "Create")</strong>
                            </div>
                            <table id="table" data-resizable="false" data-toggle="table" data-pagination="true" data-search="true" data-cookie="true" data-cookie-id-table="saveId" data-click-to-select="true" data-toolbar="#toolbar">
                                <thead>
                                    <tr>
                                        <th>
                                            Họ Tên
                                        </th>
                                        <th>
                                            Giới Tính
                                        </th>
                                            <th>
                                                Địa Chỉ
                                            </th>
                                            <th>
                                                Ngày Sinh
                                            </th>
                                            <th>
                                                CMND
                                            </th>
                                            <th>
                                                Cơ Quan
                                            </th>
                                            <th>
                                               Khen Thưởng
                                            </th>
                                            <th>
                                                Kỷ Luật
                                            </th>
                                            <th data-width="200px"></th>
                                    </tr>
                                </thead>
                                <tbody>

                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.CbHoten)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.CbGioitinh)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.CbDiachi)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.CbNgaysinh)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.CbCmnd)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.CoquanCqMaNavigation.CqTen)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.KhenthuongcbKtcbMaNavigation.KtcbThanhtich)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.KyluatcbKlcbMaNavigation.KlcbHt )
                                            </td>
                                            <td>
                                                <a asp-action="Details" asp-route-id="@item.CbMa" class="btn btn-custon-rounded-three btn-success"><i class="fa fa-info-circle"></i></a> 
                                                <a asp-action="Edit" asp-route-id="@item.CbMa" class="btn btn-custon-rounded-three btn-warning"><i class="fa fa-edit"></i></a> 
                                                <a asp-action="Delete" asp-route-id="@item.CbMa" class="btn btn-custon-rounded-three btn-danger"><i class="fa fa-trash"></i></a>
                                                <a asp-action="Print" asp-controller="Canbos" asp-route-id="@item.CbMa" class="btn btn-custon-three btn-info" style="color:white;" type="button" target="_blank">In</a>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>

                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Canbos/Print.cshtml
@model QLTHPT.Models.Canbo

@{
    ViewData["Title"] = "Print";
    Layout = null;
}

<html>
<head>
	<link href="~/mystyle.css" rel="stylesheet" />
</head>
<style>
    h2 {
        text-align: center;
        text-transform: uppercase;
        color: black;
        }
    p{
        margin-top: 10%;
    }
    .imgcontainer {
      text-align: center;
      margin-top: 10px;
      margin: 24px;
      width: 100%;
        }
</style>

<body onload="window.print()">
	<div class="book">
        <div class="page">
            <div class="subpage">
                <h2>THÔNG TIN CÁN BỘ</h2>
                <div class="imgcontainer">
                    <img src="~/img/edit1.jpg" alt="">
                </div>
                <p>Mã cán bộ: @Model.CbMa | Họ và tên: @Model.CbHoten</p>
                <p>Giới tính: @Model.CbGioitinh</p>
                <p>Địa chỉ: @Model.CbDiachi</p>
                <p>CMND: @Model.CbCmnd</p>
            </div>
        </div>
    </div>
</body>
</html>