Models/Thoikhoabieu.cs
using System;
using System.Collections.Generic;

namespace QLTHPT.Models
{
    public partial class Thoikhoabieu
    {
        public string TkbMa { get; set; }
        public string LopLopMa { get; set; }
        public string MonhocMhMa { get; set; }
        public string ThuThuMa { get; set; }
        public string TiethocThMa { get; set; }
        public string CanboCbMa { get; set; }
        public string HockyHkMa { get; set; }

        public virtual Canbo CanboCbMaNavigation { get; set; }
        public virtual Hocky HockyHkMaNavigation { get; set; }
        public virtual Lop LopLopMaNavigation { get; set; }
        public virtual Monhoc MonhocMhMaNavigation { get; set; }
        public virtual Thu ThuThuMaNavigation { get; set; }
        public virtual Tiethoc TiethocThMaNavigation { get; set; }
    }
}

Controllers/ThoikhoabieusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using QLTHPT.Models;

namespace QLTHPT.Controllers {
    public class ThoikhoabieusController : Controller {
        private readonly acomptec_qlthptContext _context = new acomptec_qlthptContext ();

        // GET: Thoikhoabieus
        public async Task<IActionResult> Index () {
            var acomptec_qlthptContext = _context.Thoikhoabieu.Include (t => t.CanboCbMaNavigation).Include (t => t.HockyHkMaNavigation).Include (t => t.LopLopMaNavigation).Include (t => t.MonhocMhMaNavigation).Include (t => t.ThuThuMaNavigation).Include (t => t.TiethocThMaNavigation);
            return View (await acomptec_qlthptContext.ToListAsync ());
        }

        // GET: Thoikhoabieus/Details/5
        public async Task<IActionResult> Details (string id) {
            if (id == null) {
                return NotFound ();
            }

            var thoikhoabieu = await _context.Thoikhoabieu
                .Include (t => t.CanboCbMaNavigation)
                .Include (t => t.HockyHkMaNavigation)
                .Include (t => t.LopLopMaNavigation)
                .Include (t => t.MonhocMhMaNavigation)
                .Include (t => t.ThuThuMaNavigation)
                .Include (t => t.TiethocThMaNavigation)
                .FirstOrDefaultAsync (m => m.TkbMa == id);
            if (thoikhoabieu == null) {
                return NotFound ();
            }

            return View (thoikhoabieu);
        }
        // GET: Thoikhoabieus/Print/5
        public async Task<IActionResult> Print (string id) {
            if (id == null) {
                return NotFound ();
            }

            var thoikhoabieu = await _context.Thoikhoabieu
                .FirstOrDefaultAsync (m => m.TkbMa == id);
            if (thoikhoabieu == null) {
                return NotFound ();
            }

            return View (thoikhoabieu);
        }
        // GET: Thoikhoabieus/Create
        public IActionResult Create () {
            ViewData["CanboCbMa"] = new SelectList (_context.Canbo, "CbMa", "CbMa");
            ViewData["HockyHkMa"] = new SelectList (_context.Hocky, "HkMa", "HkMa");
            ViewData["LopLopMa"] = new SelectList (_context.Lop, "LopMa", "LopMa");
            ViewData["MonhocMhMa"] = new SelectList (_context.Monhoc, "MhMa", "MhMa");
            ViewData["ThuThuMa"] = new SelectList (_context.Thu, "ThuMa", "ThuMa");
            ViewData["TiethocThMa"] = new SelectList (_context.Tiethoc, "ThMa", "ThMa");
            return View ();
        }

        // POST: Thoikhoabieus/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create ([Bind ("TkbMa,LopLopMa,MonhocMhMa,ThuThuMa,TiethocThMa,CanboCbMa,HockyHkMa")] Thoikhoabieu thoikhoabieu) {
            if (ModelState.IsValid) {
                _context.Add (thoikhoabieu);
                await _context.SaveChangesAsync ();
                return RedirectToAction (nameof (Index));
            }
            ViewData["CanboCbMa"] = new SelectList (_context.Canbo, "CbMa", "CbMa", thoikhoabieu.CanboCbMa);
            ViewData["HockyHkMa"] = new SelectList (_context.Hocky, "HkMa", "HkMa", thoikhoabieu.HockyHkMa);
            ViewData["LopLopMa"] = new SelectList (_context.Lop, "LopMa", "LopMa", thoikhoabieu.LopLopMa);
            ViewData["MonhocMhMa"] = new SelectList (_context.Monhoc, "MhMa", "MhMa", thoikhoabieu.MonhocMhMa);
            ViewData["ThuThuMa"] = new SelectList (_context.Thu, "ThuMa", "ThuMa", thoikhoabieu.ThuThuMa);
            ViewData["TiethocThMa"] = new SelectList (_context.Tiethoc, "ThMa", "ThMa", thoikhoabieu.TiethocThMa);
            return View (thoikhoabieu);
        }

        // GET: Thoikhoabieus/Edit/5
        public async Task<IActionResult> Edit (string id) {
            if (id == null) {
                return NotFound ();
            }

            var thoikhoabieu = await _context.Thoikhoabieu.FindAsync (id);
            if (thoikhoabieu == null) {
                return NotFound ();
            }
            ViewData["CanboCbMa"] = new SelectList (_context.Canbo, "CbMa", "CbMa", thoikhoabieu.CanboCbMa);
            ViewData["HockyHkMa"] = new SelectList (_context.Hocky, "HkMa", "HkMa", thoikhoabieu.HockyHkMa);
            ViewData["LopLopMa"] = new SelectList (_context.Lop, "LopMa", "LopMa", thoikhoabieu.LopLopMa);
            ViewData["MonhocMhMa"] = new SelectList (_context.Monhoc, "MhMa", "MhMa", thoikhoabieu.MonhocMhMa);
            ViewData["ThuThuMa"] = new SelectList (_context.Thu, "ThuMa", "ThuMa", thoikhoabieu.ThuThuMa);
            ViewData["TiethocThMa"] = new SelectList (_context.Tiethoc, "ThMa", "ThMa", thoikhoabieu.TiethocThMa);
            return View (thoikhoabieu);
        }

        // POST: Thoikhoabieus/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit (string id, [Bind ("TkbMa,LopLopMa,MonhocMhMa,ThuThuMa,TiethocThMa,CanboCbMa,HockyHkMa")] Thoikhoabieu thoikhoabieu) {
            if (id != thoikhoabieu.TkbMa) {
                return NotFound ();
            }

            if (ModelState.IsValid) {
                try {
                    _context.Update (thoikhoabieu);
                    await _context.SaveChangesAsync ();
                } catch (DbUpdateConcurrencyException) {
                    if (!ThoikhoabieuExists (thoikhoabieu.TkbMa)) {
                        return NotFound ();
                    } else {
                        throw;
                    }
                }
                return RedirectToAction (nameof (Index));
            }
            ViewData["CanboCbMa"] = new SelectList (_context.Canbo, "CbMa", "CbMa", thoikhoabieu.CanboCbMa);
            ViewData["HockyHkMa"] = new SelectList (_context.Hocky, "HkMa", "HkMa", thoikhoabieu.HockyHkMa);
            ViewData["LopLopMa"] = new SelectList (_context.Lop, "LopMa", "LopMa", thoikhoabieu.LopLopMa);
            ViewData["MonhocMhMa"] = new SelectList (_context.Monhoc, "MhMa", "MhMa", thoikhoabieu.MonhocMhMa);
            ViewData["ThuThuMa"] = new SelectList (_context.Thu, "ThuMa", "ThuMa", thoikhoabieu.ThuThuMa);
            ViewData["TiethocThMa"] = new SelectList (_context.Tiethoc, "ThMa", "ThMa", thoikhoabieu.TiethocThMa);
            return View (thoikhoabieu);
        }

        // GET: Thoikhoabieus/Delete/5
        public async Task<IActionResult> Delete (string id) {
            if (id == null) {
                return NotFound ();
            }

            var thoikhoabieu = await _context.Thoikhoabieu
                .Include (t => t.CanboCbMaNavigation)
                .Include (t => t.HockyHkMaNavigation)
                .Include (t => t.LopLopMaNavigation)
                .Include (t => t.MonhocMhMaNavigation)
                .Include (t => t.ThuThuMaNavigation)
                .Include (t => t.TiethocThMaNavigation)
                .FirstOrDefaultAsync (m => m.TkbMa == id);
            if (thoikhoabieu == null) {
                return NotFound ();
            }

            return View (thoikhoabieu);
        }

        // POST: Thoikhoabieus/Delete/5
        [HttpPost, ActionName ("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed (string id) {
            var thoikhoabieu = await _context.Thoikhoabieu.FindAsync (id);
            _context.Thoikhoabieu.Remove (thoikhoabieu);
            await _context.SaveChangesAsync ();
            return RedirectToAction (nameof (Index));
        }

        private bool ThoikhoabieuExists (string id) {
            return _context.Thoikhoabieu.Any (e => e.TkbMa == id);
        }
    }
}

Views/Thoikhoabieus/Create.cshtml
@model QLTHPT.Models.Thoikhoabieu

@{
    ViewData["Title"] = "Create";
}

<div class="data-table-area mg-b-15">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="sparkline13-list shadow-reset">
                    <div class="sparkline13-hd">
                        <div class="main-sparkline13-hd">
                            <h4><strong>Tạo Mới</strong></h4>
                        </div>
                    </div>
                    <div class="sparkline13-graph">
                    <form asp-action="Create">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group"  style="text-align: left;">
                            <label asp-for="TkbMa" class="control-label">Mã</label>
                            <input asp-for="TkbMa" class="form-control" />
                            <span asp-validation-for="TkbMa" class="text-danger"></span>
                        </div>
                       <div class="form-group" style="text-align: left;">
                            <label asp-for="LopLopMa" class="control-label">Lớp</label>
                            <select asp-for="LopLopMa" class ="form-control" asp-items="ViewBag.LopLopMa"></select>
                        </div>
                        <div class="form-group"  style="text-align: left;">
                            <label asp-for="MonhocMhMa" class="control-label">Môn học</label>
                            <select asp-for="MonhocMhMa" class ="form-control" asp-items="ViewBag.MonhocMhMa"></select>
                        </div>
                        <div class="form-group"  style="text-align: left;">
                            <label asp-for="ThuThuMa" class="control-label">Thứ</label>
                            <select asp-for="ThuThuMa" class ="form-control" asp-items="ViewBag.ThuThuMa"></select>
                        </div>
                        <div class="form-group"  style="text-align: left;">
                            <label asp-for="TiethocThMa" class="control-label">Tiết học</label>
                            <select asp-for="TiethocThMa" class ="form-control" asp-items="ViewBag.TiethocThMa"></select>
                        </div>
                        <div class="form-group"  style="text-align: left;">
                            <label asp-for="CanboCbMa" class="control-label">Cán bộ</label>
                            <select asp-for="CanboCbMa" class ="form-control" asp-items="ViewBag.CanboCbMa"></select>
                        </div>
                        <div class="form-group"  style="text-align: left;">
                            <label asp-for="HockyHkMa" class="control-label">Học kỳ</label>
                            <select asp-for="HockyHkMa" class ="form-control" asp-items="ViewBag.HockyHkMa"></select>
                        </div>
                        <div class="form-group" style="text-align: left;">
                            <input type="submit" value="Tạo" class="btn btn-default"/>
                            <a asp-action="Index"class=" btn btn-custon-rounded-three btn-primary"><i class="fa fa-undo"></i></a>
                        </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div> 

Views/Thoikhoabieus/Delete.cshtml
@model QLTHPT.Models.Thoikhoabieu

@{
    ViewData["Title"] = "Delete";
}

<div class="data-table-area mg-b-15">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="sparkline13-list shadow-reset">
                    <div class="sparkline13-hd">
                        <div class="main-sparkline13-hd">
                            <h4>
                                <strong>
                                    Xóa
                                </strong>
                            </h4>
                        </div>
                    </div>
                    <h5>Bạn có chắc muốn xóa ?</h5>

                    <div class="sparkline10-graph">
                        <div class="card-body">
                            <table id="bootstrap-data-table" class="table table-striped table-bordered">
                                <thead>
                                    <tr>
                                        <th>
                                            Mã
                                        </th>
                                        <th>
                                            Cán Bộ
                                        </th>
                                        <th>
                                            Học kỳ
                                        </th>
                                        <th>
                                            Lớp
                                        </th>
                                        <th>
                                            Môn học
                                        </th>
                                        <th>
                                            Thứ
                                        </th>
                                        <th>
                                            Tiết học
                                        </th>

                                    </tr>
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(model => model.TkbMa)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(model => model.CanboCbMaNavigation.CbMa)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(model => model.HockyHkMaNavigation.HkMa)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(model => model.LopLopMaNavigation.LopMa)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(model => model.MonhocMhMaNavigation.MhMa)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(model => model.ThuThuMaNavigation.ThuMa)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(model => model.TiethocThMaNavigation.ThMa)
                                        </td>
                                    </tr>
                                </thead>

                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div>
     <form asp-action="Delete">
        <input type="hidden" asp-for="TkbMa" />
        <input type="submit" value="Xoá" class="btn btn-default" /> |
        <a asp-action="Index"class=" btn btn-custon-rounded-three btn-primary"><i class="fa fa-undo"></i></a>
    </form>
</div>

Views/Thoikhoabieus/Details.cshtml
@model QLTHPT.Models.Thoikhoabieu

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Thoikhoabieu</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CanboCbMaNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CanboCbMaNavigation.CbMa)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HockyHkMaNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HockyHkMaNavigation.HkMa)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LopLopMaNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LopLopMaNavigation.LopMa)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MonhocMhMaNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MonhocMhMaNavigation.MhMa)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ThuThuMaNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ThuThuMaNavigation.ThuMa)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TiethocThMaNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TiethocThMaNavigation.ThMa)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.TkbMa">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div> 

Views/Thoikhoabieus/Edit.cshtml
@model QLTHPT.Models.Thoikhoabieu

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Thoikhoabieu</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="TkbMa" />
            <div class="form-group">
                <label asp-for="LopLopMa" class="control-label"></label>
                <select asp-for="LopLopMa" class="form-control" asp-items="ViewBag.LopLopMa"></select>
                <span asp-validation-for="LopLopMa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MonhocMhMa" class="control-label"></label>
                <select asp-for="MonhocMhMa" class="form-control" asp-items="ViewBag.MonhocMhMa"></select>
                <span asp-validation-for="MonhocMhMa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ThuThuMa" class="control-label"></label>
                <select asp-for="ThuThuMa" class="form-control" asp-items="ViewBag.ThuThuMa"></select>
                <span asp-validation-for="ThuThuMa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TiethocThMa" class="control-label"></label>
                <select asp-for="TiethocThMa" class="form-control" asp-items="ViewBag.TiethocThMa"></select>
                <span asp-validation-for="TiethocThMa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CanboCbMa" class="control-label"></label>
                <select asp-for="CanboCbMa" class="form-control" asp-items="ViewBag.CanboCbMa"></select>
                <span asp-validation-for="CanboCbMa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HockyHkMa" class="control-label"></label>
                <select asp-for="HockyHkMa" class="form-control" asp-items="ViewBag.HockyHkMa"></select>
                <span asp-validation-for="HockyHkMa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Thoikhoabieus/Index.cshtml
@model IEnumerable<QLTHPT.Models.Thoikhoabieu>

@{
    ViewData["Title"] = "Index";
}

<div class="data-table-area mg-b-15">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="sparkline13-list shadow-reset">
                    <div class="sparkline13-hd">
                        <div class="main-sparkline13-hd">
                            <h4><strong>THỜI KHÓA BIỂU</strong></h4>
                        </div>
                    </div>
                    <div class="sparkline13-graph">
                        <div class="datatable-dashv1-list custom-datatable-overright">
                            <div id="toolbar">
                                <strong>@Html.ActionLink("Tạo Mới", "Create")</strong>
                            </div>
                            <table id="table" data-resizable="false" data-toggle="table" data-pagination="true" data-search="true" data-cookie="true" data-cookie-id-table="saveId" data-click-to-select="true" data-toolbar="#toolbar">
                                <thead>
                                    <tr>
                                        <th data-width="100px">
                                            Mã
                                        </th>
                                        <th data-width="150px">
                                            Cán Bộ
                                        </th>
                                        <th>
                                            Học kỳ
                                        </th>
                                        <th data-width="100px">
                                            Lớp
                                        </th>
                                        <th>
                                            Môn học
                                        </th>
                                        <th>
                                            Thứ
                                        </th>
                                        <th>
                                            Tiết học
                                        </th>
                                        <th data-width="200px"></th>
                                    </tr>
                                </thead>
                                <tbody>

                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.TkbMa)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.CanboCbMaNavigation.CbHoten)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.HockyHkMaNavigation.HkTen)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.LopLopMaNavigation.LopTen)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.MonhocMhMaNavigation.MhTen)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.ThuThuMaNavigation.ThuTen)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.TiethocThMaNavigation.ThTen)
                                            </td>
                                            <td>
                                                <a asp-action="Details" asp-route-id="@item.TkbMa" class="btn btn-custon-rounded-three btn-success"><i class="fa fa-info-circle"></i></a> 
                                                <a asp-action="Edit" asp-route-id="@item.TkbMa" class="btn btn-custon-rounded-three btn-warning"><i class="fa fa-edit"></i></a> 
                                                <a asp-action="Delete" asp-route-id="@item.TkbMa" class="btn btn-custon-rounded-three btn-danger"><i class="fa fa-trash"></i></a>                                           
                                                <a asp-action="Print" asp-controller="Thoikhoabieus" asp-route-id="@item.TkbMa" class="btn btn-custon-three btn-info" style="color:white;" type="button" target="_blank">In</a>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>

                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@* 
<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CanboCbMaNavigation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HockyHkMaNavigation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LopLopMaNavigation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MonhocMhMaNavigation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ThuThuMaNavigation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TiethocThMaNavigation)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CanboCbMaNavigation.CbMa)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HockyHkMaNavigation.HkMa)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LopLopMaNavigation.LopMa)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MonhocMhMaNavigation.MhMa)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ThuThuMaNavigation.ThuMa)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TiethocThMaNavigation.ThMa)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.TkbMa">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.TkbMa">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.TkbMa">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table> *@

Views/Thoikhoabieus/Print.cshtml
@model QLTHPT.Models.Thoikhoabieu

@{
    ViewData["Title"] = "Print";
    Layout = null;
}

<html>
<head>
	<link href="~/mystyle.css" rel="stylesheet" />
</head>
<style>
    h2 {
        text-align: center;
        text-transform: uppercase;
        color: black;
        }
    p{
        margin-top: 10%;
    }
</style>

<body onload="window.print()">
	<div class="book">
        <div class="page">
            <div class="subpage">
                <h2>THỜI KHÓA BIỂU</h2>
                <p>Mã lớp: @Model.LopLopMa | Giáo viên phụ trách: @Model.CanboCbMa</p>
                <p>Học kỳ: @Model.HockyHkMa</p>
                <p>Thứ: @Model.ThuThuMa</p>
                <p>Tiết học: @Model.TiethocThMa : Môn học: @Model.MonhocMhMa</p>
            </div>
        </div>
    </div>
</body>
</html>